update legacy CHI
bayaraa/d2gl pull request #74
Opened 2023-07-10 12:03 UTC by CaiMiao

this PR includes below changes:

- changed `CHI` in order to strictly matching legacy Traditional Chinese version published by [Unalis](https://zh.wikipedia.org/zh-tw/%E6%9D%BE%E5%B4%97%E7%A7%91%E6%8A%80)
- add `SIN` from D2R `zhCN` as placeholder
- add/replace `g_death_text_others` texts of `POR`/`RUS` from D2R `ruRU` by the way
- none of these changes include coordinate position adjustment

Some facts:

- Diablo II never got official Russian / Portuguese language support, until D2R got realeased
- The `SIN` language code is initially intended to be used by Simplified Chinese, but got discontinued for unknown reason. Code leftovers just existed, however.
- There was an [official legacy Simplified Chinese version](http://redump.org/disc/82671/), published by [Aomei ](https://zh.wikipedia.org/zh-cn/%E5%A5%A5%E7%BE%8E%E7%94%B5%E5%AD%90), using `CHI` language code. But it is no longer acknowledged by Blizzard, due to CD-KEY duplicate selling issue.

2023-07-10 13:19 UTC, bayaraa commented
Hi. thing is it doesn't work with just changing texts.
Need actual SIN version UI dc6 files. Because they are probably different than CHI version right?
How it drawing esc option text is checking cell count/width/height dc6 images.
```cpp
{ 0, {  74, 54 }, L"选项" }, // OPTIONS
```
0 = cell count
74 = width
54 = height
of options.dc6.

2023-07-10 13:38 UTC, bayaraa commented
> there is no SIN version as SIN reuses most CHI assets, as of current actual code behavior
You mean all UI image sizes exactly same as CHI version?
If it's slight different (like 1px diff) it wont switch to HD text.

2023-07-10 13:58 UTC, bayaraa commented
ah. now i get it. you just copied files from chi to sin right.

2023-07-10 14:41 UTC, CaiMiao commented
> ah. now i get it. you just copied ui files from chi to sin right.

IIRC you don't even need to copy. It's hardcoded to use `CHI`'s assets.

2023-07-10 16:15 UTC, bayaraa requested changes

2023-07-11 04:43 UTC, bayaraa commented on d2gl/src/modules/hd_text/variables.h
> +		{ 1, {  23, 36 }, L"You lost gold" }, // youdiedsoftcore.dc6
this i understand

2023-07-11 04:46 UTC, bayaraa commented on d2gl/src/modules/hd_text/variables.h
> +		{ 1, { 124, 41 }, L"You lost gold" }, // You lost gold
i saw somewhere this maybe older d2 versions, i might be mistaken.
What i dont get is why did you change completely normal russian text to english even tho its not used ingame.

2023-07-13 02:56 UTC, bayaraa approved these changes

2023-07-13 02:56 UTC, merged